In [17]:
import numpy as np
import pandas as pd

In [18]:
x=[1,4,6,7,4,8]
nx=np.array(x)

In [19]:
print(nx)

[1 4 6 7 4 8]


In [20]:
print(nx.shape)

(6,)


In [21]:
ny=np.array([[1,2,3],[2,5,6]])
print(ny.shape)

(2, 3)


In [22]:
ny

array([[1, 2, 3],
       [2, 5, 6]])

In [23]:
data=np.arange(1,100,0.2)
data

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [24]:
#how many may values are
print(data.size)

495


In [25]:
#no of values it calculate distance by own
data1=np.linspace(0,100,200)
data1

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [26]:
data3=np.random.rand(100)
data3

array([0.6583187 , 0.78123374, 0.82014845, 0.78353019, 0.27760973,
       0.96468039, 0.16531021, 0.08109951, 0.14370434, 0.36853921,
       0.95726519, 0.39263951, 0.92881484, 0.11859856, 0.97714409,
       0.03310693, 0.23997127, 0.79515323, 0.58026893, 0.99456881,
       0.56401762, 0.19493381, 0.93154904, 0.25527281, 0.36703336,
       0.31670555, 0.89695008, 0.53857276, 0.16157041, 0.11788115,
       0.5928347 , 0.15779503, 0.47699975, 0.48899595, 0.0962374 ,
       0.43229339, 0.4026521 , 0.63009738, 0.87965809, 0.40455736,
       0.67830815, 0.40352116, 0.97270738, 0.69937878, 0.65749811,
       0.02984855, 0.84624597, 0.05056268, 0.77705015, 0.85147335,
       0.88040428, 0.69670974, 0.72006686, 0.59505141, 0.75023023,
       0.56254339, 0.90230277, 0.24580558, 0.14239197, 0.28664746,
       0.13073649, 0.24503835, 0.87980582, 0.12219178, 0.27794471,
       0.09737986, 0.37369911, 0.91556771, 0.73230553, 0.46805573,
       0.39680189, 0.07153731, 0.18085461, 0.30475966, 0.22914

In [27]:
#1se 10 ke ek no 100 baar repeat krna

In [28]:
n4=np.random.randint(1,10,(10,10))
n4

array([[8, 3, 8, 9, 6, 3, 8, 9, 2, 6],
       [3, 9, 4, 7, 7, 7, 1, 1, 5, 8],
       [4, 5, 2, 9, 9, 9, 1, 2, 7, 5],
       [8, 4, 2, 9, 6, 7, 5, 1, 5, 8],
       [9, 9, 8, 7, 6, 3, 5, 8, 3, 9],
       [4, 9, 1, 8, 1, 9, 4, 1, 2, 9],
       [5, 7, 2, 9, 5, 9, 6, 8, 4, 8],
       [2, 6, 1, 3, 3, 1, 1, 9, 2, 4],
       [9, 7, 6, 6, 8, 5, 1, 6, 8, 9],
       [4, 9, 5, 3, 6, 1, 1, 4, 7, 3]])

In [29]:
n4.reshape(10,10)

array([[8, 3, 8, 9, 6, 3, 8, 9, 2, 6],
       [3, 9, 4, 7, 7, 7, 1, 1, 5, 8],
       [4, 5, 2, 9, 9, 9, 1, 2, 7, 5],
       [8, 4, 2, 9, 6, 7, 5, 1, 5, 8],
       [9, 9, 8, 7, 6, 3, 5, 8, 3, 9],
       [4, 9, 1, 8, 1, 9, 4, 1, 2, 9],
       [5, 7, 2, 9, 5, 9, 6, 8, 4, 8],
       [2, 6, 1, 3, 3, 1, 1, 9, 2, 4],
       [9, 7, 6, 6, 8, 5, 1, 6, 8, 9],
       [4, 9, 5, 3, 6, 1, 1, 4, 7, 3]])

In [30]:
data4.reshape((10,5,2))
data4

NameError: name 'data4' is not defined

In [ ]:
data*10


array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
       120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140.,
       142., 144., 146., 148., 150., 152., 154., 156., 158., 160., 162.,
       164., 166., 168., 170., 172., 174., 176., 178., 180., 182., 184.,
       186., 188., 190., 192., 194., 196., 198., 200., 202., 204., 206.,
       208., 210., 212., 214., 216., 218., 220., 222., 224., 226., 228.,
       230., 232., 234., 236., 238., 240., 242., 244., 246., 248., 250.,
       252., 254., 256., 258., 260., 262., 264., 266., 268., 270., 272.,
       274., 276., 278., 280., 282., 284., 286., 288., 290., 292., 294.,
       296., 298., 300., 302., 304., 306., 308., 31

In [ ]:
n6=np.random.randint(1,10,10)

In [ ]:
n7=np.random.randint(1,3,4)
n7


array([1, 1, 1, 1])

In [ ]:
n4

3

In [ ]:
n4.flatten()

array([7, 5, 9, 1, 2, 1, 2, 4, 1, 9, 5, 1, 7, 9, 7, 1, 4, 5, 9, 4, 5, 6,
       3, 8, 3, 3, 2, 9, 3, 1, 2, 8, 9, 6, 7, 5, 6, 8, 7, 5, 5, 6, 2, 4,
       3, 8, 3, 2, 7, 9, 7, 6, 8, 5, 8, 7, 3, 9, 9, 5, 9, 2, 8, 2, 3, 3,
       9, 1, 8, 1, 6, 4, 3, 9, 5, 7, 1, 5, 2, 2, 4, 2, 1, 2, 1, 7, 2, 8,
       5, 6, 8, 7, 2, 4, 4, 3, 5, 7, 8, 9])

In [31]:
n4.sum()

540

In [32]:
n4.sum(axis=0)

array([56, 68, 39, 70, 57, 54, 33, 49, 45, 69])

In [34]:
a=np.random.randint(1,100,(3,2))
b=np.random.randint(1,100,(3,2))
print(a)
print(b)

[[33 11]
 [86 63]
 [ 5 58]]
[[ 4 26]
 [40 28]
 [56 59]]


In [35]:
np.hstack((a,b))

array([[33, 11,  4, 26],
       [86, 63, 40, 28],
       [ 5, 58, 56, 59]])

In [36]:
np.vstack((a,b))

array([[33, 11],
       [86, 63],
       [ 5, 58],
       [ 4, 26],
       [40, 28],
       [56, 59]])

In [37]:
np.vstack((a, c.T))

NameError: name 'c' is not defined

In [ ]:
m=np.array(1,5,6,8,6,7,4,8,2,4,9,7,3,1,3,8,6,4,3,)
